title: Infra Notes
description: Notes by Sharim
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Notes Repository: https://github.com/sharimkhan01/infra-notes/
  
color_scheme: dark
